import 'package:d_rocket_builder/src/rest/parser.dart';

/// Emite el código Dart para una [ParsedClient].
///
/// Movido desde `d_rest_build/lib/emitter.dart` ( del roadmap
/// de d_rocket). El codegen ahora produce código que importa de
/// `package:d_rocket/d_rocket.dart` (que reexporta `RestRequest`,
/// `dRest`, `invokeRequest`, `@RestClient` originales de `d_rest`).
String emitClient(ParsedClient client) {
  final StringBuffer buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by d_rocket_builder:rest_client.');
  buffer.writeln('// Source: ${client.className}');
  buffer.writeln();
  buffer.writeln('// ignore_for_file: type=lint, prefer_single_quotes');
  buffer.writeln();
  buffer.writeln("part of '${_toSnakeCase(client.className)}.dart';");
  buffer.writeln();

  // === Concrete class ===
  buffer.writeln('class _\$${client.className} implements ${client.className} {');
  buffer.writeln('  _\$${client.className}();');
  buffer.writeln();
  buffer.writeln('  /// Crea una instancia del cliente tipado.');
  buffer.writeln('  static ${client.className} create() => _\$${client.className}();');
  buffer.writeln();

  for (final ParsedMethod method in client.methods) {
    _emitMethod(buffer, client, method);
  }

  buffer.writeln('}');
  return buffer.toString();
}

void _emitMethod(StringBuffer buffer, ParsedClient client, ParsedMethod method) {
  final String returnTypeStr = _methodReturnTypeString(method);
  final String fullPath = '${client.classPath}${method.path}';

  buffer.writeln('  @override');
  buffer.writeln(
    '  $returnTypeStr ${method.name}(${_parameterList(method)}) async {',
  );

  // Build headers literal
  buffer.writeln('    final Map<String, String> _headers = <String, String>{');
  for (final MapEntry<String, String> e in client.classHeaders.entries) {
    buffer.writeln("      '${_escape(e.key)}': '${_escape(e.value)}',");
  }
  for (final MapEntry<String, String> e in method.methodHeaders.entries) {
    buffer.writeln("      '${_escape(e.key)}': '${_escape(e.value)}',");
  }
  buffer.writeln('    };');

  // Header params (from @Header)
  final List<ParsedParameter> headerParams = method.parameters
      .where((ParsedParameter p) => p.kind == ParamKind.header)
      .toList();
  if (headerParams.isNotEmpty) {
    buffer.writeln('    _headers.addAll(<String, String>{');
    for (final ParsedParameter p in headerParams) {
      final String key = p.annotationName ?? p.name;
      buffer.writeln("      '${_escape(key)}': '\$${p.name}'.toString(),");
    }
    buffer.writeln('    });');
  }

  // Path params
  final List<ParsedParameter> pathParams = method.parameters
      .where((ParsedParameter p) => p.kind == ParamKind.path)
      .toList();
  String pathParamsValue = 'const <String, Object>{}';
  if (pathParams.isNotEmpty) {
    buffer.writeln('    final Map<String, Object> _pathParams = <String, Object>{');
    for (final ParsedParameter p in pathParams) {
      final String key = p.annotationName ?? p.name;
      buffer.writeln("      '$key': \$${p.name} as Object,");
    }
    buffer.writeln('    });');
    pathParamsValue = '_pathParams';
  }

  // Query params
  final List<ParsedParameter> queryParams = method.parameters
      .where((ParsedParameter p) => p.kind == ParamKind.query)
      .toList();
  String queryParamsValue = 'const <String, String>{}';
  if (queryParams.isNotEmpty) {
    buffer.writeln('    final Map<String, String> _query = <String, String>{');
    for (final ParsedParameter p in queryParams) {
      final String key = p.annotationName ?? p.name;
      buffer.writeln("      '$key': \$${p.name}.toString(),");
    }
    buffer.writeln('    });');
    queryParamsValue = '_query';
  }

  // Body
  final List<ParsedParameter> bodyParams = method.parameters
      .where((ParsedParameter p) =>
          p.kind == ParamKind.body || p.kind == ParamKind.rawBody)
      .toList();
  String bodyExpr = 'null';
  if (bodyParams.isNotEmpty) {
    final ParsedParameter p = bodyParams.first;
    if (p.kind == ParamKind.rawBody) {
      bodyExpr = '\$${p.name}';
    } else {
      bodyExpr = "dRest.encodeBody<${p.dartType}>(\$${p.name})";
    }
  }

  // Build the request
  final String baseUrlLiteral = _quoteString(client.baseUrl);
  buffer.writeln('    final RestRequest _request = RestRequest(');
  buffer.writeln("      method: '${method.verb}',");
  buffer.writeln("      path: ${_quoteString(fullPath)},");
  buffer.writeln('      baseUrl: $baseUrlLiteral,');
  buffer.writeln('      headers: _headers,');
  if (bodyParams.isNotEmpty) {
    buffer.writeln('      body: $bodyExpr,');
  }
  if (queryParams.isNotEmpty) {
    buffer.writeln('      queryParameters: $queryParamsValue,');
  }
  if (pathParams.isNotEmpty) {
    buffer.writeln('      pathParameters: $pathParamsValue,');
  }
  if (client.classTimeout != null) {
    buffer.writeln('      timeout: ${_durationLiteral(client.classTimeout!)},');
  }
  buffer.writeln('    );');

  // Return statement
  if (method.returnType.isVoid) {
    buffer.writeln('    await invokeRequest<void>(');
    buffer.writeln('      _request,');
    buffer.writeln('      (dynamic data) => null,');
    buffer.writeln('    );');
  } else if (method.returnType.isDynamic) {
    buffer.writeln('    return invokeRequest<dynamic>(');
    buffer.writeln('      _request,');
    buffer.writeln('      (dynamic data) => data,');
    buffer.writeln('    );');
  } else {
    final String t = method.returnType.dartType;
    buffer.writeln('    return invokeRequest<$t>(');
    buffer.writeln('      _request,');
    buffer.writeln('      (dynamic data) => dRest.decodeBody<$t>(data),');
    buffer.writeln('    );');
  }

  buffer.writeln('  }');
  buffer.writeln();
}

String _methodReturnTypeString(ParsedMethod method) {
  if (method.returnType.isVoid) return 'Future<void>';
  if (method.returnType.isList) {
    final String inner = method.returnType.innerType ?? 'dynamic';
    return 'Future<List<$inner>>';
  }
  if (method.returnType.isMap) {
    return 'Future<${method.returnType.dartType}>';
  }
  return 'Future<${method.returnType.dartType}>';
}

String _parameterList(ParsedMethod method) {
  final List<String> parts = <String>[];
  for (final ParsedParameter p in method.parameters) {
    final String required = p.isRequired ? 'required ' : '';
    parts.add('$required${p.dartType} ${p.name}');
  }
  return parts.join(', ');
}

String _quoteString(String value) {
  return "'${value.replaceAll(r'\', r'\\\\').replaceAll("'", r"\'")}'";
}

String _escape(String value) {
  return value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
}

String _durationLiteral(Duration d) {
  return 'Duration(microseconds: ${d.inMicroseconds})';
}

String _toSnakeCase(String input) {
  final StringBuffer result = StringBuffer();
  for (int i = 0; i < input.length; i++) {
    final int code = input.codeUnitAt(i);
    if (code >= 65 && code <= 90) {
      if (i > 0) result.write('_');
      result.write(String.fromCharCode(code + 32));
    } else {
      result.write(input[i]);
    }
  }
  return result.toString();
}
