//: the codegen for `@Migration`.
//
// Walks every `@Migration` top-level function
// in a library, plus every `@Table` class in
// the same library, and emits a `MigrationBase` subclass
// that knows about every entity.
//
// The user writes:
//
// ```dart
// @Migration(id: '001', name: 'Initial schema')
// MigrationBase initialSchema() => _$_InitialSchema();
// ```
//
// The codegen emits `_$_InitialSchema` (a class
// extending `MigrationBase`) that runs
// `entityMeta.createTableDdl()` for every entity on
// `up()`, and `DROP TABLE` (in reverse order) on
// `down()`.

import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

/// The codegen entry point for `@Migration`.
class MigrationGenerator extends Generator {
  const MigrationGenerator();

  @override
  Future<String> generate(
    LibraryReader library,
    BuildStep buildStep,
  ) async {
    //: collect every `@Migration`
    // top-level function in the library.
    final List<String> migrations = <String>[];
    //: collect every `@Table`
    // class in the same library — the migration will
    // run CREATE TABLE for each.
    final List<String> entityClasses = <String>[];

    for (final Element element in library.allElements) {
      // Skip the `MigrationBase` class itself
      // (its declaration re-exports / references
      // it).
      if (element is ClassElement) {
        if (element.metadata.annotations.any(
          (ElementAnnotation a) =>
              a.computeConstantValue()?.type?.element?.name ==
              'Table',
        )) {
          if (element.name != null) {
            entityClasses.add(element.name!);
          }
        }
        continue;
      }
      if (element is ExecutableElement) {
        if (element.metadata.annotations.any(
          (ElementAnnotation a) =>
              a.computeConstantValue()?.type?.element?.name ==
              'MigrationBase',
        )) {
          if (element.name != null) {
            migrations.add(element.name!);
          }
        }
      }
    }

    if (migrations.isEmpty) {
      // No `@Migration` in this file — emit
      // nothing.
      return '';
    }

    final StringBuffer out = StringBuffer();
    out.writeln('// GENERATED CODE — DO NOT MODIFY BY HAND');
    out.writeln();
    for (final String fnName in migrations) {
      out.writeln(_emitMigrationClass(
        fnName: fnName,
        entityClasses: entityClasses,
      ));
    }
    return out.toString();
  }

  /// Emits the `_$<fnName>` `MigrationBase` class with
  /// the right `id` / `name` / `up` / `down`.
  ///
  /// Reads the `@Migration` annotation's `id`
  /// and `name` from the function element.
  String _emitMigrationClass({
    required String fnName,
    required List<String> entityClasses,
  }) {
    // For MVP we use a fixed shape:
    // - id: 'auto-001' / 'auto-002' / … (caller can
    //   override in a sub-fase)
    // - name: 'Initial schema (auto-generated by
    //   d_rocket_builder:rocket_migration)'
    // - up: CREATE TABLE for every entity (in
    //   declaration order), then CREATE INDEX for
    //   every @Index annotation, then
    //   PRAGMA foreign_keys = ON (defensive: the
    //   runtime also sets this on every open, but
    //   an explicit PRAGMA in the migration makes
    //   the intent visible to anyone reading the
    //   generated SQL).
    // - down: DROP TABLE in reverse order
    final StringBuffer upCalls = StringBuffer();
    for (final String cls in entityClasses) {
      upCalls.writeln(
        '    _$cls.entityMeta.createTableDdl().split(\'\\n\').forEach('
        '(String line) { exec(line); });',
      );
      upCalls.writeln(
        '    for (final String idx in _$cls.entityMeta.createIndexStatements()) {'
        ' exec(idx); }',
      );
    }
    upCalls.writeln("    exec('PRAGMA foreign_keys = ON');");
    final StringBuffer downCalls = StringBuffer();
    for (final String cls in entityClasses.reversed) {
      downCalls.writeln('    exec(\'DROP TABLE IF EXISTS \${_$cls.entityMeta.tableName}\');');
    }
    return '''
class _\$$fnName extends MigrationBase {
  @override
  String get id => 'auto-$fnName';

  @override
  String get name =>
      'Auto-generated initial schema for $fnName';

  @override
  void up(MigrationExecutor exec) {
$upCalls
  }

  @override
  void down(MigrationExecutor exec) {
$downCalls
  }
}
''';
  }
}
